### ISSUE TITLE
참고 문의

### ISSUE THREAD

**Issue by ljlm0402** [changhoi/ts-backend-template#1]
개발자님 블로그를 멋진 포스팅 감사합니다.

다름이 아니라, 현재 익스프레스 스타터 패키지를 만들어서 오픈소스로 배포한 개발자입니다.

이번 오픈소스에 추가 사항이 typeorm인데 
해당 레포도 워낙 퀄리티 있으셔서 추후에 참고가 가능할지 궁금합니다.

아무런 얘기도 없이 참고하는건 예의가 아닌거 같아서 이슈 남깁니다.
물론 카피를 하겠다는 얘기가 아닌 기본적인 패턴이나 구현 방식을 참고할려고 합니다.
감사합니다 :-D

**Comment by changhoi** [comment]
아 넵 그렇게 봐주셔서 감사하네요. 편하게 사용하셔도 됩니다.
